### ISSUE TITLE
Incomplete metrics when using month 12

### ISSUE THREAD

**Issue by dgreen-bris** [agathangelidis/hotspell#1]
Hi,

I hope you are well!

I am looking to use the hotspell python package to calculate heatwave metrics over Africa as part of my masters's project. After reading the documentation and README files, I cannot seem to resolve an issue when defining my summer months to include month 12. 

Specifically, it runs the hotspell.heatwaves module with no error codes, but for instance, when looking at HWF, years with no HWF value are not included in the produced dataframe. This issue is not replicated when using months 1-11, where the yearly values with no occurrence are included in the dataframe.  I have tested on the Berkeley Earth and ERA5-Land datasets, producing the same issue. This issues also occurs on the other metrics during my analyses.

I have provided a screenshot of when the HWF function does not produce the number of HWF for each year, when using month 12, and when it does work for other months. Additionally, I have provided the code used to produce error, to see if I am referencing the package incorrectly.

Is this an issue with the way I am referencing the hotspell package?

All the best,

Dan

[HOTSPELL_SUMMER_MONTH.txt](https://github.com/agathangelidis/hotspell/files/8969548/HOTSPELL_SUMMER_MONTH.txt)
<img width="307" alt="HOTSPELL_SUMMER_DATAFRAME_INCLUDING_MONTH_12" src="https://user-images.githubusercontent.com/93319860/175362640-2547bd77-c90d-4d2e-b5e8-d4d1db6a06a1.PNG">
<img width="77" alt="HOTSPELL_SUMMER_DATAFRAME_NOT_INCLUDING_MONTH_12" src="https://user-images.githubusercontent.com/93319860/175362876-0d2290fa-f1ab-4b5e-b3b4-c40806199366.PNG">

**Comment by agathangelidis** [comment]
This has been fixed in the latest version of the library.
Thank you for pointing out!
