### ISSUE TITLE
Error when importing CSVs

### ISSUE THREAD

**Issue by nj935** [agathangelidis/hotspell#2]
When I try to load a CSV, I get the following error:

> File ~/opt/anaconda3/envs/ox/lib/python3.11/site-packages/hotspell/heatwaves.py:265, in _compute_daily_thresholds(daily_windows, timeseries_ref_period, hw_index, summer_months)
>     262 else:
>     263     daily_thresholds["threshold"] = hw_index.fixed_thres
> --> 265 daily_thresholds = daily_windows.join(daily_thresholds.drop("window", 1))
>     266 return daily_thresholds
> 

> TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 were given

My data is correctly formatted. I think the error may be fixed by changing the code to daily_thresholds.drop("window",axis=1))

**Comment by agathangelidis** [comment]
Yes, you are correct. New versions of pandas don't allow passing a non-keyword argument for axis. Would you like to make a pull request with this change?

**Comment by agathangelidis** [comment]
It has been fixed in the latest release.
